// <auto-generated />
using System;
using MD;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MD.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MD.Cto.CtoMarcacionesReporte", b =>
                {
                    b.Property<decimal>("CantidadHorasFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CodigoEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSucursal")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Entrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HorasJustificadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasMarcadas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("HorasReglamentarias")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Salida")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sucursal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TiempoAFavor")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TiempoEnContra")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("CtoMarcacionesReporte");
                });

            modelBuilder.Entity("MD.Entidades.Empleado", b =>
                {
                    b.Property<int>("CodigoEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("CodigoHorario")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSucursal")
                        .HasColumnType("int");

                    b.Property<int>("CodigoUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuarioElimina")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuarioMod")
                        .HasColumnType("int");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaMod")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEliminado")
                        .HasColumnType("bit");

                    b.Property<string>("NombreEmpleado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodigoEmpleado");

                    b.HasIndex("CodigoHorario");

                    b.HasIndex("CodigoSucursal");

                    b.ToTable("Empleado");
                });

            modelBuilder.Entity("MD.Entidades.Horario", b =>
                {
                    b.Property<int>("CodigoHorario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoHorario"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Inicia")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Termina")
                        .HasColumnType("datetime2");

                    b.HasKey("CodigoHorario");

                    b.ToTable("Horario");

                    b.HasData(
                        new
                        {
                            CodigoHorario = 1,
                            Descripcion = "Manana",
                            Inicia = new DateTime(1, 1, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActivo = true,
                            Termina = new DateTime(1, 1, 1, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            CodigoHorario = 2,
                            Descripcion = "Tarde",
                            Inicia = new DateTime(1, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActivo = true,
                            Termina = new DateTime(1, 1, 1, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MD.Entidades.Justificacion", b =>
                {
                    b.Property<int>("CodigoJustificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoJustificacion"));

                    b.Property<int>("CodigoEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("CodigoEstado")
                        .HasColumnType("int");

                    b.Property<int>("CodigoTipoJustificacion")
                        .HasColumnType("int");

                    b.Property<int>("CodigoUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuarioElimina")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuarioMod")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaMod")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraFinal")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicial")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Horas")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("IsEliminado")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeriado")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPermiso")
                        .HasColumnType("bit");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoJustificacion");

                    b.HasIndex("CodigoEmpleado");

                    b.HasIndex("CodigoTipoJustificacion");

                    b.ToTable("Justificacion");
                });

            modelBuilder.Entity("MD.Entidades.Marcacion", b =>
                {
                    b.Property<int>("IdMarcacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMarcacion"));

                    b.Property<int>("CodigoEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("CodigoSucursal")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("IdMarcacion");

                    b.HasIndex("CodigoEmpleado");

                    b.HasIndex("CodigoSucursal");

                    b.ToTable("Marcacion");
                });

            modelBuilder.Entity("MD.Entidades.Menu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuId");

                    b.ToTable("Menu");

                    b.HasData(
                        new
                        {
                            MenuId = 1,
                            Modulo = "Empleados",
                            NombreMenu = "Empleado"
                        },
                        new
                        {
                            MenuId = 2,
                            Modulo = "Empleados",
                            NombreMenu = "Justificaciones"
                        },
                        new
                        {
                            MenuId = 3,
                            Modulo = "Empleados",
                            NombreMenu = "Reportes"
                        },
                        new
                        {
                            MenuId = 4,
                            Modulo = "Seguridad",
                            NombreMenu = "Roles"
                        },
                        new
                        {
                            MenuId = 5,
                            Modulo = "Emmpresa",
                            NombreMenu = "Sucursales"
                        });
                });

            modelBuilder.Entity("MD.Entidades.MenusOpciones", b =>
                {
                    b.Property<int>("MenuOpcionesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuOpcionesId"));

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<string>("NombreOpcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MenuOpcionesId");

                    b.HasIndex("MenuId");

                    b.ToTable("MenusOpciones");

                    b.HasData(
                        new
                        {
                            MenuOpcionesId = 4,
                            MenuId = 2,
                            NombreOpcion = "Agregar"
                        },
                        new
                        {
                            MenuOpcionesId = 5,
                            MenuId = 2,
                            NombreOpcion = "Modificar"
                        },
                        new
                        {
                            MenuOpcionesId = 6,
                            MenuId = 2,
                            NombreOpcion = "Eliminar"
                        },
                        new
                        {
                            MenuOpcionesId = 7,
                            MenuId = 2,
                            NombreOpcion = "Aprobar"
                        },
                        new
                        {
                            MenuOpcionesId = 8,
                            MenuId = 2,
                            NombreOpcion = "Rechazar"
                        },
                        new
                        {
                            MenuOpcionesId = 1,
                            MenuId = 1,
                            NombreOpcion = "Agregar"
                        },
                        new
                        {
                            MenuOpcionesId = 2,
                            MenuId = 1,
                            NombreOpcion = "Modificar"
                        },
                        new
                        {
                            MenuOpcionesId = 3,
                            MenuId = 1,
                            NombreOpcion = "Eliminar"
                        });
                });

            modelBuilder.Entity("MD.Entidades.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            IsActivo = true,
                            NombreRol = "Admin"
                        });
                });

            modelBuilder.Entity("MD.Entidades.RolMenu", b =>
                {
                    b.Property<int>("RolMenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolMenuId"));

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("RolMenuId");

                    b.HasIndex("RolId");

                    b.ToTable("RolMenu");

                    b.HasData(
                        new
                        {
                            RolMenuId = 1,
                            IsActivo = true,
                            MenuId = 1,
                            RolId = 1
                        },
                        new
                        {
                            RolMenuId = 2,
                            IsActivo = true,
                            MenuId = 2,
                            RolId = 1
                        },
                        new
                        {
                            RolMenuId = 3,
                            IsActivo = true,
                            MenuId = 3,
                            RolId = 1
                        },
                        new
                        {
                            RolMenuId = 4,
                            IsActivo = true,
                            MenuId = 4,
                            RolId = 1
                        },
                        new
                        {
                            RolMenuId = 5,
                            IsActivo = true,
                            MenuId = 5,
                            RolId = 1
                        });
                });

            modelBuilder.Entity("MD.Entidades.RolMenuOpciones", b =>
                {
                    b.Property<int>("RolMenuOpcionesid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolMenuOpcionesid"));

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<int>("MenuOpcionesId")
                        .HasColumnType("int");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<int>("RolMenuId")
                        .HasColumnType("int");

                    b.HasKey("RolMenuOpcionesid");

                    b.HasIndex("RolMenuId");

                    b.ToTable("RolMenuOpciones");
                });

            modelBuilder.Entity("MD.Entidades.Sucursal", b =>
                {
                    b.Property<int>("CodigoSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoSucursal"));

                    b.Property<int>("CodigoUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuarioElimina")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuarioMod")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaMod")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActivo")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsEliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CodigoSucursal");

                    b.ToTable("Sucursal");

                    b.HasData(
                        new
                        {
                            CodigoSucursal = 1,
                            CodigoUsuarioCreacion = 1,
                            FechaCreacion = new DateTime(2024, 9, 21, 15, 7, 52, 557, DateTimeKind.Local).AddTicks(528),
                            IsActivo = true,
                            IsEliminado = false,
                            Nombre = "Linda Vista"
                        },
                        new
                        {
                            CodigoSucursal = 2,
                            CodigoUsuarioCreacion = 1,
                            FechaCreacion = new DateTime(2024, 9, 21, 15, 7, 52, 557, DateTimeKind.Local).AddTicks(541),
                            IsActivo = true,
                            IsEliminado = false,
                            Nombre = "Metrocentro"
                        });
                });

            modelBuilder.Entity("MD.Entidades.TipoJustificacion", b =>
                {
                    b.Property<int>("CodigoTipoJustificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoTipoJustificacion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActiva")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeriado")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSalida")
                        .HasColumnType("bit");

                    b.HasKey("CodigoTipoJustificacion");

                    b.ToTable("TipoJustificacion");

                    b.HasData(
                        new
                        {
                            CodigoTipoJustificacion = 1,
                            Descripcion = "Dia Vacaciones",
                            IsActiva = true,
                            IsFeriado = false,
                            IsSalida = true
                        },
                        new
                        {
                            CodigoTipoJustificacion = 2,
                            Descripcion = "Horas Libre",
                            IsActiva = true,
                            IsFeriado = false,
                            IsSalida = true
                        },
                        new
                        {
                            CodigoTipoJustificacion = 3,
                            Descripcion = "Dia Feriado",
                            IsActiva = true,
                            IsFeriado = false,
                            IsSalida = true
                        },
                        new
                        {
                            CodigoTipoJustificacion = 4,
                            Descripcion = "Horas Extras",
                            IsActiva = true,
                            IsFeriado = false,
                            IsSalida = false
                        });
                });

            modelBuilder.Entity("MD.Entidades.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CodigoUsuarioCreacion")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuarioElimina")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuarioMod")
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorreoElectronico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaMod")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsEliminado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            CodigoUsuarioCreacion = 1,
                            Contrasena = "123",
                            CorreoElectronico = "",
                            FechaCreacion = new DateTime(2024, 9, 21, 15, 7, 52, 557, DateTimeKind.Local).AddTicks(653),
                            IsEliminado = false,
                            Nombre = "admin",
                            RolId = 1
                        });
                });

            modelBuilder.Entity("MD.Entidades.Empleado", b =>
                {
                    b.HasOne("MD.Entidades.Horario", "Horario")
                        .WithMany("Empleados")
                        .HasForeignKey("CodigoHorario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MD.Entidades.Sucursal", "Sucursal")
                        .WithMany("Empleados")
                        .HasForeignKey("CodigoSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Horario");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("MD.Entidades.Justificacion", b =>
                {
                    b.HasOne("MD.Entidades.Empleado", "Empleado")
                        .WithMany("Justificaciones")
                        .HasForeignKey("CodigoEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MD.Entidades.TipoJustificacion", "TipoJustificacion")
                        .WithMany("Justificaciones")
                        .HasForeignKey("CodigoTipoJustificacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("TipoJustificacion");
                });

            modelBuilder.Entity("MD.Entidades.Marcacion", b =>
                {
                    b.HasOne("MD.Entidades.Empleado", "Empleado")
                        .WithMany("Marcaciones")
                        .HasForeignKey("CodigoEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MD.Entidades.Sucursal", "Sucursal")
                        .WithMany("Marcaciones")
                        .HasForeignKey("CodigoSucursal")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("MD.Entidades.MenusOpciones", b =>
                {
                    b.HasOne("MD.Entidades.Menu", "Menu")
                        .WithMany("Opciones")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Menu");
                });

            modelBuilder.Entity("MD.Entidades.RolMenu", b =>
                {
                    b.HasOne("MD.Entidades.Rol", "Rol")
                        .WithMany("RolMenus")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MD.Entidades.RolMenuOpciones", b =>
                {
                    b.HasOne("MD.Entidades.RolMenu", "RolMenu")
                        .WithMany("RolMenuOpciones")
                        .HasForeignKey("RolMenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RolMenu");
                });

            modelBuilder.Entity("MD.Entidades.Usuario", b =>
                {
                    b.HasOne("MD.Entidades.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MD.Entidades.Empleado", b =>
                {
                    b.Navigation("Justificaciones");

                    b.Navigation("Marcaciones");
                });

            modelBuilder.Entity("MD.Entidades.Horario", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("MD.Entidades.Menu", b =>
                {
                    b.Navigation("Opciones");
                });

            modelBuilder.Entity("MD.Entidades.Rol", b =>
                {
                    b.Navigation("RolMenus");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MD.Entidades.RolMenu", b =>
                {
                    b.Navigation("RolMenuOpciones");
                });

            modelBuilder.Entity("MD.Entidades.Sucursal", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Marcaciones");
                });

            modelBuilder.Entity("MD.Entidades.TipoJustificacion", b =>
                {
                    b.Navigation("Justificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
